version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ylcqv49z5v6i"
s3_prefix = "resume-challenge"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
